### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Nayee123#1]
[Infografía Nayeli Anai Gonzáles López.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Nayee123/files/10841429/Infografia.Nayeli.Anai.Gonzales.Lopez.pdf)

**Comment by Rmz-Rigo** [comment]
Calificacion: 19/20
Faltan las referencias

**Comment by josealfredo79** [comment]
Bien hecho y revisado
